version: '3.9'

services:
  front:
    image: esthg/front
    ports:
      - 5000:5000

  back:
    image: esthg/back
    ports:
      - 8080:8080
    command: ./server
    environment:
      - REDIS_HOST=reddis
      - POSTGRES_HOST=db

  reddis:
    image: redis:latest

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - $HOME/dockerdevops/lab/TEMOP/database:/var/lib/postgresql/data

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
